### ISSUE TITLE
[DESIGN] - Gas Exchange System

### ISSUE THREAD

**Issue by JLefebvre55** [OpenFormTech/PeaPod#107]
**Completion is tracked in the linked PR.**

## Design Scope

Design a system to mediate gas exchange between the internal environment and the surroundings.

### Purpose

The purpose of the gas exchange system is to control the exhaust of internal air and the intake of fresh air to maintain a desired concentration of CO2/O2/etc. while a) not introducing pathogens and/or other aerosols, and b) not compromising the precision of the internal environment.

### Function

Inputs:
- Power
- Exchange control signals (fan speed and shutter open/close)

Outputs:
- Gas intake (from surroundings), gas exhaust (to surroundings)

It interfaces with/depends on the following systems:
- Power delivery

System operation assumes:
- External environment can handle exhaust air (i.e. higher humidity and O2 concentrations are not detrimental)

### Method

Setup:
1. Connect exhaust port to external exhaust air treatment system (i.e. dehumidification)

Process:
1. On-demand, both input and output ports activate (shutters open, fans are enabled)
2. Input port draws in air from surroundings
3. Output port expels air through filtration and dehumidification system to be recycled

Shutdown:
1. Disconnect exhaust port from filtration/dehumidification system

## Features

> Each feature should be added to relevant BoMs and CADs where applicable. Design decisions should be well-supported using relevant research and calculations, and should be documented in the Solution Overview. If a feature is complex enough, create a new issue for it using this template, and tag it here.

- Exchange Ports (Input and Output)
    - Fan: Controls exchange rate
    - Design _Shutter Mechanism_
    - Input and Output Filters: HEPA filter for the removal of pathogens
- Gas Concentration Sensors: CO2, etc. Used to inform automation when to trigger exchange
- Control Loop: Dead-Zone Bang-Bang

## Requirements and Validation

*What does this design need to accomplish? How do we know it has accomplished this?*

List any applicable metrics with criteria/constraints, applicable to purpose, function, method, and each feature, as well as how to test them.

1. Maximum gas exchange throughput -> complete air replacement for a 4-unit setup in X minutes
2. Filtration > 99% of pathogens (viral, bacterial, and otherwise) as well as aerosols (pollen, etc.)
3. Shutter mechanism is air-tight (~0% throughput) when closed

## Verification

> Each test should be performed and documented, and the testing documentation attached to the PR. The testing suite should address the full scope of the function (i.e. ensure inputs are met and outputs work), method (all steps execute correctly), and features (each feature performs as expected) with respect to the purpose and requirements.

*How does this design achieve its method effectively, safely, and reliably? How do we test this?*

Specific testing procedure:

1. Test shutter and fan operation
2. Test shutter air-tightness
3. Test air throughput (maximum and control precision)
4. Test aerosol filtration(?)

**Additional context**

Add any other context about the design scope or additional deliverables here.

*Add any relevant electronics to the Wiring Diagram*

**Comment by JLefebvre55** [comment]
## ToDo:

- [x]  ~~Choose a fan~~ **We use [this](https://www.digikey.ca/en/products/detail/qualtek/FAD1-12025CBHW12/2600106) 120mm fan**
    - [ ]  Add to BoM
    - [ ]  Add to CAD
    - [ ]  Test operation
- [x]  ~~Choose HEPA filter~~ **[3881T101](https://www.mcmaster.com/3881T101)**
    - [ ]  Document justification with respect to requirements (filter particulate size): [This](https://www.grainger.com/know-how/equipment-information/kh-what-is-merv-rating-air-filter-rating-chart) page says that a MERV rating of >13 is required to filter all pathogens
    - [ ]  Add to BoM
    - [ ]  Add to CAD
    - [ ]  Test filtration capabilities (?)
- [ ]  Design *Shutter Mechanism*
- [x]  ~~Choose CO2 sensor~~ **[K30 Extended Range](https://github.com/UofTAgritech/PeaPod/issues/1)**
    - [ ]  Document justification with respect to requirements (sensor range, precision, read interval)
    - [x]  Add to BoM
    - [ ]  Add to PCB (breakout?) -> CAD
    - [ ]  Write code and test
- [ ]  Design housing for fans, filters, and shutters
- [ ]  Fabricate and assemble subsystem
- [ ]  Test all features, document results
- [ ]  Write code to trigger operation on CO2 status
