### ISSUE TITLE
[DOCS] - Testing Procedure

### ISSUE THREAD

**Issue by JLefebvre55** [OpenFormTech/PeaPod#118]
Detail out a testing plan for each of the following criteria. Must include _processes_, list of _measurements_ to be taken, and planned _experiments_.

- [x] Acceptability
- [x] Safety of Process
- [x] Safety of Outputs
- [x] Resource Outputs
- [x] Reliability and Stability of Outputs

In addition, detail out a:
- [x] Sample Collection Procedure and Schedule

**Comment by JLefebvre55** [comment]
## Todo:

_By Feb 10th_:
- [x] _Acceptability_: Determine specific procedure for double-blind "taste-test". Something like "Given 5 output species, participants will be divided 50/50 at random to rate commercial/control samples against PeaPod/test samples against 4 criteria (appearance, aroma, flavour, texture) on a 9-point scale"
- [x] _Safety of Process_, _Safety of Outputs_, _Reliability/Stability_: What is total aerobic plate count? How do we test that, as well as ATP testing?
- [x] _Resource Outputs_: How do we perform nutritional analysis (what materials and equipment)?
- [x] Basic outline for each criterion
- [x] Add references for each testing procedure - has it been done before? how do we know this is sufficient?

**Comment by JLefebvre55** [comment]
Done!
