### ISSUE TITLE
[DOCS] - HACCP

### ISSUE THREAD

**Issue by JLefebvre55** [OpenFormTech/PeaPod#119]
Detail out the following:
- [x] Food Production System Description (incl. flowchart) - @JLefebvre55 
- [x] Critical Points
- [x] Standard Test Record

**Comment by JLefebvre55** [comment]
## Todo:

_By Feb 10th_:
- [x] Learn jargon (critical points, standard test record, etc.), read [this](https://www.fda.gov/food/hazard-analysis-critical-control-point-haccp/haccp-principles-application-guidelines)
- [x] Determine critical points

**Comment by JLefebvre55** [comment]
Done!
