### ISSUE TITLE
[DESIGN] - Air Thermoregulation & Circulation

### ISSUE THREAD

**Issue by JLefebvre55** [OpenFormTech/PeaPod#122]
**Completion is tracked in the linked PR.**

## Design Scope

Design a thermoelectric (Peltier) air heating/cooling and circulation mechanism (heat sinks + fans + tiles + driver + control system).

### Purpose

The purpose of the air thermoregulation system is to maintain a desired leaf-zone air temperature, and to circulate air for homogeneity (humidity, temperature, gasses) and pollination.

### Function

Inputs:
- Power to driver
- Thermoregulation signals (heat pump direction +/- and % power)
- Circulation control signal (% fan speed)

Outputs:
- Heat (either into or out from system)

It interfaces with/depends on the following systems:
- Power systems
- Automation

System operation assumes:
- Power is delivered

### Method

Process:
1. Air is circulated throughout the environment for temperature homogeneity
2. Temperature is measured, sent to automation
3. Automation controls heat pump speed and direction, circulation fan speed

## Features
> Each feature should be added to relevant BoMs and CADs where applicable. Design decisions should be well-supported using relevant research and calculations, and should be documented in the Solution Overview. If a feature is complex enough, create a new issue for it using this template, and tag it here.

- _Circulation Fans_
- _Temperature Sensors_
- _Heat Pump_
   - _Peltier Devices_: Solid-state thermoelectric tiles pump heat from one face to the other (proportionate to current).
   - _Heat Sinks_: Aluminum blocks with fins to hold and exchange heat between the air and Peltier devices (both sides). Mating face coated with thermal compound.
   - _Heat Sink Fans_: For waste heat dissipation to external environment.
- #120 
- _Control System_: PID control loop

## Requirements and Validation

_What does this design need to accomplish? How do we know it has accomplished this?_

List any applicable metrics with criteria/constraints, applicable to purpose, function, method, and each feature, as well as how to test them.
1. Power output > heat loss of system at temperature extremes (see Solution Overview for numbers)
2. Heat input minus heat loss of system -> heating from one temperature extreme to the other in 60sec

## Verification
> Each test should be performed and documented, and the testing documentation attached to the PR. The testing suite should address the full scope of the **function** (i.e. ensure inputs are met and outputs work), **method** (all steps execute correctly), and **features** (each feature performs as expected) with respect to the purpose and requirements.

_How does this design achieve its method effectively, safely, and reliably? How do we test this?_

Specific testing procedure:
1. Heat pump direction and magnitude respond to control signal as expected
2. Fans operate as expected
3. Heat pump power exceeds maximum heat loss (temperature extremes)
4. Heat pump power exceeds that required to reach temperature extremes in under sixty (60) seconds given the system's heat capacity

**Additional context**

Add any other context about the design scope or additional deliverables here.

_Add any electrical power lines and/or signals to wiring diagram_

**Comment by JLefebvre55** [comment]
## Background

- "To find the average heat loss per unit area, simply divide the temperature difference by the R-value for the layer." https://en.wikipedia.org/wiki/R-value_(insulation)#Calculating_heat_loss
- Peltier driver resource: https://www.ti.com/lit/an/slua979a/slua979a.pdf "It is more accurate to use **constant current** [to drive a Peltier tile] than voltage drive as its _impedance varies with temperature_"
- Peltier tile intro and selection: https://www.cuidevices.com/blog/how-to-select-a-peltier-module
- Peltier systems design: https://www.cuidevices.com/blog/how-to-design-a-peltier-module-system
- "Thermal impedance ... represents how much the [system] temperature will rise above the [surrounding] temperature ... for every Watt of power dissipated within the [system]." https://www.cuidevices.com/blog/how-to-select-a-heat-sink

## ToDo

- [x] ~~Determine max/min desired environment air temperature, and typical ambient temperatures~~ **10C-35C internal, 22C external**
- [x] ~~Determine max heat loss/gain of system from ambient at internal extremes~~ **-62.42W, 57.61W**
- [x] ~~Determine power needed to reach extremes from ambient in 120sec~~ **-64.13W, 59.19W**
- [x] ~~Select _Peltier Modules_ -~~ **[CP854345H](https://www.digikey.ca/en/products/detail/cui-devices/CP854345H/6217110)** (70W)
- [x] ~~Determine thermal resistance~~ **<= 0.329 C/W**
- [ ] Select _Heat Sinks_
- [ ] Select _Circulation and Heat Sink Fans_
- [ ] #120 
- [ ] _Temperature Sensor and  Control System_
   - [x] ~~Select Temperature Sensor~~ [SHT31-D Breakout](https://www.digikey.ca/en/products/detail/adafruit-industries-llc/2857/5804106) by [Adafruit](https://www.adafruit.com/product/2857)
   - [ ] PID Loop
   
### Notes on Motor Driver (TI DRV8432)

Two H-bridges, PWM-dimmable, Vsource up to 52V, output current up to 14A constant (when running both amplifiers+bridges in "parallel mode")

Integrated Undervoltage, Overtemperature, Overload, and Short Circuit protection

[Reference design](https://www.ti.com/lit/ug/slou291a/slou291a.pdf?ts=1638441432380)

**Comment by JLefebvre55** [comment]
Transferred from UofT Agritech
