### ISSUE TITLE
[DESIGN] - Mesh Nebulizer Driver Circuit

### ISSUE THREAD

**Issue by JLefebvre55** [OpenFormTech/PeaPod#129]
**Completion is tracked in the linked PR.**

## Design Scope

Design a driver circuit for a mesh nebulizer.

### Purpose

The purpose of the driver circuit is to cause the piezoelectric mesh disc to oscillate.

### Function

Inputs:
- VDD (IC/MOSFET gate/logic voltage)
- VCC (disc voltage is +/- VCC)
- Enable/disable signal (0V or VDD)

Outputs:
- AC sinusoid (+VCC to -VCC, constant frequency)

It interfaces with/depends on the following systems:
- Automation

System operation assumes:
- Water supply
- Power

### Method

1. _Square Wave Generator_: Astable 555 IC (input: on/off signal, VDD; output: 0V/5V square wave, fixed frequency, ~50% duty cycle)
2. _Inverter Stage_: MOSFET H-bridge (input: square wave, VCC; output: -VCC/+VCC square wave, same properties)
3. _Filter Stage_: 3-stage RC filter (input: square wave; output: sine wave)
4. _Power Stage_

## Requirements and Validation

_What does this design need to accomplish? How do we know it has accomplished this?_

List any applicable metrics with criteria/constraints, applicable to purpose, function, method, and each feature, as well as how to test them.
1. Power consumption when off
2. Efficiency when on

## Verification
> Each test should be performed and documented, and the testing documentation attached to the PR. The testing suite should address the full scope of the **function** (i.e. ensure inputs are met and outputs work), **method** (all steps execute correctly), and **features** (each feature performs as expected) with respect to the purpose and requirements.

_How does this design achieve its method effectively, safely, and reliably? How do we test this?_

Specific testing procedure:
1. Generates ideal sinusoid

**Additional context**

Add any other context about the design scope or additional deliverables here.

**Comment by JLefebvre55** [comment]
**WIP Simulation**: [Here](https://tinyurl.com/2lbwu583)

## Background

Reference design:
https://www.youtube.com/watch?v=aKhPj7uFD0Y
https://www.youtube.com/watch?v=OOZi3QnnDCo

## ToDo

- [x] Design astable timer stage (select passive component values)
- [x] Design inverter stage (push-pull)
- [x] Design filter stage (select passive component values)
- [x] Design power stage
- [x] Simulate circuit
- [ ] Select/order breadboard components, test w/o load (oscilloscope verification)
- [ ] Design PCB, reselect components
- [ ] Determine piezoelectric disc requirements (VCC, frequency) and characteristics (R, C, L)
- [ ] Order PCB, components
