### ISSUE TITLE
[FEATURE] - README Overhaul

### ISSUE THREAD

**Issue by JLefebvre55** [OpenFormTech/PeaPod#13]
`README.md` has some useless clog, and is missing useful stuff. See https://www.makeareadme.com/.

### Context

Features/sections we **MUST** have:
- [X] Project Name
- [x] Description (include some visuals, i.e. a 3D GIF of the CAD, maybe a flowchart/diagram)
    - [x] Features list
    - [ ] Background
    - [x] Differences from alternatives
- [x] Production
    - [x] Assembly
    - [x] Installation
    - [ ] Usage (w/ examples, i.e. GIF of expected output, inline code)
- [x] Contribution (maybe add guidelines and adapt to a `CONTRIBUTING.md`
    - [x] Development (dependencies, environment, language)
    - [ ] Support (issues page, discussion board/Discord?)
    - [x] Roadmap (adapted from milestones/project boards)
- [x] Acknowledgements (authors, UTAG)

Other useful files:
- [X] License
- [ ] Changelog?

**Comment by JLefebvre55** [comment]
Done!
