### ISSUE TITLE
[DESIGN] - Automation Software, Cloud Backend

### ISSUE THREAD

**Issue by JLefebvre55** [OpenFormTech/PeaPod#130]
**Completion is tracked below.**

## Design Scope

Design and implement all software libraries and scripts for the automation subsystem.

### Purpose

The purpose of the automation subsystem software suite is to enable sensor reading, actuator control, camera capture, environment schedule parsing and implementation, and cloud monitoring and control.

### Method

See software control flow diagram.

**Comment by JLefebvre55** [comment]
## Background

## ToDo

> As of Jul 16, 2022

- [ ] Computer Software (Raspberry Pi Zero 2 W, TypeScript)
   - [ ] Main Menu/Idle State
   - [x]  Check env fields on import
   - [ ] Camera capture (w/ lighting control)
   - [ ] Controller Interface Class
      - [x] Message parsing
      - [x] Publisher start → Pull arduino reset → Revision listener → write initial instructions
      - [x] Implement compile and flash (update) util function
      - [x] Test board-to-board ICSP programming
      - [ ] Test automated flashing on revision fail
   - [ ] Control Systems Classes
      - [ ] PID (Air, Water temp)
      - [ ] Bang-Bang (Humidity, Gas Concentration)
   - [ ] Cloud Publishing Interface Class
      - [x] Firebase Device Flow, Self-Registration, Key Caching
      - [ ] Project, Program Selection
      - [ ] MQTT batch publishing (data, error, debug) and subscribing (commands, config aka environment schedule)
         - [x]  Direct arduino instruction send via GCP “command”
         - [ ]  Change data batch from “label:{batch:[{timestamp:..., value:...}, ...]}” to “label:[{timestamp:..., value:...}, ...]” (same for CloudPonics)
   - [x] Local Logging Interface Class
      
- [ ] Microcontroller Software (Arduino Nano, C/C++)
   - [x] More sophisticated sensor/actuator object states (error codes, etc.)
   - [ ]  Sensor and actuator toJSON method (names, ids, data labels)
   - [ ] Include units (str), precision (uint8_t numbers after decimal) in data messages
   - [ ] Sensor Interface Classes
      - [x] CO2 Sensor (K30 Extended Range)
      - [x] Air Temp, Hum Sensor (SHT31)
      - [ ] Water Temp Sensor
      - [ ] Water Pressure Sensor
   - [ ] Actuator Interface Classes
      - [x] Lighting
      - [x] Supply Pump, Solenoid
      - [ ] Dosage Pumps
      - [x] Peltier TEC
   - [x] JSON messaging, instruction parsing libraries
   - [ ] Main Menu/Idle State
   - [x] Accountability (WDT, error/debug codes, software revision checks, unit tests)
       - [x]  Upload/wiring (blink)
       - [x] JSON messaging
       - [x] JSON parsing, instruction implementation
       - [x]  Sensor unit tests

- [ ] Cloud Backend (Google Cloud Platform IoT Core, PubSub; Firebase PubSub, Cloud Functions, Firestore)
   - [x] MQTT subscribing (data, error, debug), send to Firestore
   - [ ] MQTT publishing (commands, config selection/updating) from CloudPonics
