### ISSUE TITLE
[DESIGN] - Humidification

### ISSUE THREAD

**Issue by JLefebvre55** [OpenFormTech/PeaPod#26]
**Completion is tracked in the linked PR.**

## Design Scope

Design an ultrasonic mesh nebulizer humidifier.

### Purpose

The purpose of the humidification system is to generate dry water vapour, increasing the relative humidity of the growth environment on demand.

### Function

Inputs:
- Power
- RO Water
- On/off control signal

Outputs:
- Dry water vapour

### Method

Process:
1. Air is circulated throughout the environment for humidity homogeneity
2. Relative humidity is measured, sent to automation
3. Automation activates humidification system if below dead-zone

## Features
> Each feature should be added to relevant BoMs and CADs where applicable. Design decisions should be well-supported using relevant research and calculations, and should be documented in the Solution Overview. If a feature is complex enough, create a new issue for it using this template, and tag it here.

- [ ] _Circulation Fans_ (part of #122)
- [ ] _Humidity Sensors_ (integrated with _Temperature Sensors_ in #122)
- [ ] _Ultrasonic Humidifier_
  - [ ] _Water Tank_
  - [ ] _Piezoelectric Disc_ (mesh vs ceramic?)
- [ ] #129
- [ ] _Bang-Bang Control System_

### Validation

Must output clean, dry vapour.

### Verification

List any applicable metrics with criteria/constraints:
1. Max humidity output (maximize)

**Comment by JLefebvre55** [comment]
Timing circuit complete and tested. See photos.
<img src="https://user-images.githubusercontent.com/30713298/122820052-2d861500-d2a9-11eb-98e7-905aaae9ed24.jpeg" width="35%"><img src="https://user-images.githubusercontent.com/30713298/122820049-2c54e800-d2a9-11eb-983c-a8be7c0e7b67.jpeg" width="65%">

**Comment by JLefebvre55** [comment]
Power circuit didn't work. Drew more than 1.5A at max and nearly overheated the MOSFET. Further testing is required.

**Comment by JLefebvre55** [comment]
Considering this issue **blocked** until i figure out what the hell's wrong with the power circuit.

**Comment by JLefebvre55** [comment]
## Background

Reference design:
https://www.youtube.com/watch?v=aKhPj7uFD0Y
https://www.youtube.com/watch?v=OOZi3QnnDCo

Some potential discs:
https://www.steminc.com/PZT/en/mist-generation-transducer

## ToDo

- [ ] Determine max/min desired environment relative humidity
- [ ] Determine vapour output target to reach extremes in 120sec
- [ ] Determine vapour droplet diameter
- [ ] Select _Piezoelectric Disc_
- [ ] Design _Water Tank_
- [ ] #129 
- [ ] Humidity Sensor and Control System
   - [x] ~~Select Temperature Sensor~~ [SHT31-D Breakout](https://www.digikey.ca/en/products/detail/adafruit-industries-llc/2857/5804106) by [Adafruit](https://www.adafruit.com/product/2857)
   - [ ] Bang-Bang Control Loop
