### ISSUE TITLE
[FEATURE] - CAD Up Aeroponics Hardware

### ISSUE THREAD

**Issue by JLefebvre55** [OpenFormTech/PeaPod#43]
Create new 3D designs for the aeroponics hardware from the real-life parts. One design per part.
- [x] Design parts
  - [x] Pump
  - [x] Accumulator tank
  - [x] All fittings
  - [ ] ~~Each length of tubing~~ [Reason](https://github.com/UTAgritech/PeaPod/issues/35#issuecomment-878865682)
  - [x] Nozzle
  - [x] Solenoid
  - [ ] ~~#48~~ don't feel like it
- [ ] ~~Add to master designs~~ [Reason](https://github.com/UTAgritech/PeaPod/issues/35#issuecomment-878865682)
