### ISSUE TITLE
[DOCS] - Design Report Animation: Storyboard

### ISSUE THREAD

**Issue by JLefebvre55** [OpenFormTech/PeaPod#55]
Create an outline of the various "scenes" of the Design Report Animation.

"_You are required to submit a 5-minute (maximum length) design animation demonstrating a simulation of your food production technology under operation. This animation should include key elements, such as: the setup, any operation from a user perspective, various inputs and outputs and the shutdown and cleaning process. It is recommended that the animation be saved on a platform that support video files (e.g., YouTube, Google Drive) and provide a link of the video in your submission._"

- Simulation under operation
  - Setup (assembly, startup)
  - Operation (autonomous, from user perspective (maintenance, #76, cleaning))
  - Inputs (Planting) and Outputs (Harvest, Seed Collection)
  - Shutdown and Stowage

### TODO:
- [x] Figure out missing/blank frames
  - [x] A3
  - [x] B1f
  - [x] B1g
  - [x] B1h
  - [x] C1
    - [x] #77 
  - [x] D2
  - [x] D3
  - [x] D4
    - [x] #81 
  - [x] D5?
    - [x] #82 
  - [x] E1
- [x] Figure out if there are any other maintenance procedures
- [x] Frames for each maintenance procedure (B2a-B2h)
- [x] Figure out all the CADs we need, open an issue (under #28)

### Notes

B1k - More abstract animation of a machine learning model? Showing data flow and "learning"
