### ISSUE TITLE
[FEATURE] - Aeroponics Solution Dosage

### ISSUE THREAD

**Issue by nchareunsouk** [OpenFormTech/PeaPod#70]
> @JLefebvre55 

**Completion is tracked in the linked PR.**

## Design Scope

Design a solution dosage system for the addition of pH balancing solutions and nutrient solutions.

### Purpose

The purpose of the solution dosage system is to add precise proportions of concentrates to the pressurized aeroponics line.

### Function

Inputs:
- Flow rate
- Dosage ON/OFF and rate (per concentrate)

Outputs:
- Precise amounts of concentrates (proportionate to solution flow)

It interfaces with/depends on the following systems:
- Power
- Automation

System operation assumes:
- Line under pressure (80PSI)

### Method

Options:
1. Venturi siphon injection: Too many unknowns, not enough pressure difference across the venturi, not directly controllable
2. Proportional flow solenoid valve (i.e. open for 5 seconds every minute) - hard to source and expensive.
3. Pre-mixing
4. Proportional injectors (piston-driven)
5. **Peristaltic pump manifold**: "Flow source" topology, rated for >80PSI back-pressure, "locked" when off, no backflow

Setup:
1. Connect pump lines to concentrate tank and manifold tee
2. Prime pump (automated; known priming time i.e. >= 5sec)

Process:
1. Primed pump is a "flow source" rated for operating back-pressure
2. Control flow of concentrates into solution line (0-12V PWM)

Shutdown:
1. Disconnect from concentrate tank and manifold

## Features
> Each feature should be added to relevant BoMs and CADs where applicable. Design decisions should be well-supported using relevant research and calculations, and should be documented in the Solution Overview. If a feature is complex enough, create a new issue for it using this template, and tag it here.

- _Peristaltic Pump_: PWM-controllable DC motor (i.e. 12V), rated for >100PSI, precise dosage
   - _Pump Line_: Soft (<70A Durometer) high-pressure (>100PSI) tubing, water-safe, probably like 3/16" OD silicone, for peristalsis operation
- _Pump Line to Tank/Manifold Lines Adapter_
- _Peristaltic Pump Driver Board_: Just PWM-able MOSFETs (faster switching, higher throughput than BJT)
- _Concentrates Tank_
   - _Concentrates Tank to Pump Line Connector_
- _Flow Rate Sensor_

## Requirements and Validation

_What does this design need to accomplish? How do we know it has accomplished this?_

List any applicable metrics with criteria/constraints, applicable to purpose, function, method, and each feature, as well as how to test them.
1. TBA

## Verification
> Each test should be performed and documented, and the testing documentation attached to the PR. The testing suite should address the full scope of the **function** (i.e. ensure inputs are met and outputs work), **method** (all steps execute correctly), and **features** (each feature performs as expected) with respect to the purpose and requirements.

_How does this design achieve its method effectively, safely, and reliably? How do we test this?_

Specific testing procedure:
1. Max Dosage Rate - ???
2. Dosage Rate Precision @ Different Amounts
4. Dosage Rate Stability @ Different Rates
5. Backflow in OFF state, ON state at operating pressure

**Comment by JLefebvre55** [comment]
Siphons have:
- Input: 3/4" hose female
- Output: 3/4" hose male
- Inlet: Fits 1/4" OD tube (with some effort)
- Spring-based check valve

**Comment by JLefebvre55** [comment]
## Todo:
- [ ] #125 
- [x] ~~Choose Flow Sensor~~ [YF-B1](https://www.seeedstudio.com/Water-Flow-Sensor-YF-B1-p-2878.html)
   - [ ] Determine maximum flow rate, needed precision
- [ ] Design Pump Driver Board
   - [x] ~~Choose Transistor~~ [MMBT2222AT-7-F](https://www.digikey.ca/en/products/detail/diodes-incorporated/MMBT2222AT-7-F/814502)
   - [x] ~~Design~~
   - [ ] Order
- [ ] Write pump control software
   - [ ] Flow sensor reading
   - [ ] Actuator, instruction matrix entry
   - [ ] Unit tests
- [ ] Assemble and Test
- [ ] Update documentation
   - [ ] Solution overview
   - [ ] Plumbing diagram
   - [ ] BoMs
   - [ ] CAD

## Background

TBA
