### ISSUE TITLE
[DESIGN] - Dehumidification

### ISSUE THREAD

**Issue by nchareunsouk** [OpenFormTech/PeaPod#74]
**Completion is tracked in the linked PR.**

## Design Scope

Design a system to decrease the air water vapour content of the internal environment.

### Purpose

The purpose of the dehumidification system is to control the "extraction" of water vapour from the internal environment while a) not introducing pathogens and/or other aerosols to the outside environment, b) minimizing waste water (aka maximizing recapture), and c) maximizing the precision of the internal environment.

*Note on scope*: We have eliminated a number of methods for dehumidification:

- Condensation (i.e. a cold surface causes vapour to collect for recapture) - introduces "cross-talk" with thermoregulation
- ...

Thus we have scoped in to *chemical extraction* via "desiccants".

### Function

Inputs:

- Power
- Dehumidification control systems (fan speed and shutter open/close)
- Dry desiccant

Outputs:

- Saturated desiccant
- Saturation indicator signal (color sensor)

It interfaces with/depends on the following systems:

- Power delivery
- Operator notification (for desiccant replacement)

System operation assumes:

- An external "oven" capable of drying saturated desiccant, with either a) ability to recapture water vapour (preferred), or b) capacity to handle water vapour

### Method

Setup:

1. Dehumidification control signals are hooked up
2. Dry desiccant is added to cartridge, which is inserted

Process:

1. Humidity sensor sends data to control module
2. Dehumidification control signal activates fans and opens shutters
3. Humid air passes over the desiccant, and dry air exits the unit
4. Desiccant becomes saturated, and indicates this
5. Indication is sensed by computer, which notifies the user
6. Cartridge is removed by the user, and swapped for a dry one. Process continues
7. Saturated cartridge is recharged

Shutdown:

1. Control signals are disconnected
2. Final recharging of cartridge
3. Desiccant is removed from cartridge

## Features

> Each feature should be added to relevant BoMs and CADs where applicable. Design decisions should be well-supported using relevant research and calculations, and should be documented in the Solution Overview. If a feature is complex enough, create a new issue for it using this template, and tag it here.

- [ ] _Humidity Sensors_ (integrated with _Temperature Sensors_ in #122)
- [ ]  Dehumidification Unit: One input port and one output port. Comprised of:
    - [ ]  Fans: Draws moist air through input port and dried air through output port.
    - [ ]  Filter: HEPA filters are located at ports of dehumidification chamber. Eliminates risk of any airborne pathogens being transferred onto silica beads.
    - [ ]  Airtight Shutters - Isolates dehumidification chamber when not in use. Prevents unintended dehumidification. Located at input and output ports. Controlled by a servo.
    - [ ]  Desiccant Cartridge: Oven-safe. Easily removable for swapping and "recharging".
    - [ ]  Silica Beads: Cheap, efficient, non-toxic desiccant. Changes color when saturated. Can be reused indefinitely when water is evaporated.

## Requirements and Validation

*What does this design need to accomplish? How do we know it has accomplished this?*

List any applicable metrics with criteria/constraints, applicable to purpose, function, method, and each feature, as well as how to test them.

1. Desiccant removes moisture from air
2. Desiccant indicates saturation as expected, which is sensed by computer
3. Shutters operate as intended, and no dehumidification occurs when closed
4. Maximum dehumidification rate exceeds total plant transpiration rate

## Verification

> Each test should be performed and documented, and the testing documentation attached to the PR. The testing suite should address the full scope of the function (i.e. ensure inputs are met and outputs work), method (all steps execute correctly), and features (each feature performs as expected) with respect to the purpose and requirements.

*How does this design achieve its method effectively, safely, and reliably? How do we test this?*

Specific testing procedure:

1. Test shutter and fan operation, shutter air-tightness (zero unintended dehumidification), and air throughput (maximum and precision)
2. Test cartridge replacement efficacy
3. Test aerosol filtration
4. Test dehumidification (maximum rate, rate control precision)

**Additional context**

Add any other context about the design scope or additional deliverables here.

**Comment by narvcharv** [comment]
[Indicating Bulk Desiccant](https://www.mcmaster.com/desiccants/indicating-bulk-desiccants/)

[Colour Sensor](https://www.adafruit.com/product/1334#technical-details)

**Comment by narvcharv** [comment]
[120mm 12V DC Fan (IP69K)](https://www.mcmaster.com/7664N16/)

**Comment by narvcharv** [comment]
- [x] Fan Hardware/Mounting
- [x] Airflow Calculations/General Metrics
- [ ] Cartridge Removal Method + Features

**Comment by narvcharv** [comment]
[Fan Mounting Screws](https://www.mcmaster.com/91502A132/)
[Fan Mounting Nuts](https://www.mcmaster.com/90591A255/)

Note to self: adjust cartridge size to accommodate fan mounting

**Comment by narvcharv** [comment]
[New fan](https://www.digikey.ca/en/products/detail/qualtek/FAD1-12025CBHW12/2600106)

**Comment by JLefebvre55** [comment]
Removed shutters to eliminate some complexity

**Comment by JLefebvre55** [comment]
Moved to https://github.com/UofTAgritech/PeaPod/issues/7

**Comment by JLefebvre55** [comment]
## ToDo:

- [x]  Preliminary calculations
    - [x]  How much desiccant do we need?
- [x]  ~~Choose desiccant~~ [2181K93](https://www.mcmaster.com/2181K93)
    - [x]  Add to BoM
    - [x]  Add to CAD
    - [ ]  Test
- [x]  ~~Choose color sensor~~ [TCS34725](https://www.digikey.ca/en/products/detail/adafruit-industries-llc/1334/5629426)
    - [ ]  Document justification with respect to requirements (sensor range, precision, read interval)
    - [x]  Add to BoM
    - [ ]  Add connection to main PCB (**[[@UofTAgritech/electronics](https://github.com/orgs/UofTAgritech/teams/electronics)](https://github.com/orgs/UofTAgritech/teams/electronics)**)
    - [ ]  Write code and test (**[[@UofTAgritech/electronics](https://github.com/orgs/UofTAgritech/teams/electronics)](https://github.com/orgs/UofTAgritech/teams/electronics)**)
- [x]  ~~Choose a fan~~ **We use [[this](https://www.digikey.ca/en/products/detail/qualtek/FAD1-12025CBHW12/2600106)](https://www.digikey.ca/en/products/detail/qualtek/FAD1-12025CBHW12/2600106) 120mm fan**
    - [ ]  Add to BoM
    - [ ]  Add to CAD
    - [ ]  Test operation
- [x]  ~~Choose HEPA filter~~ **[[3881T101](https://www.mcmaster.com/3881T101)](https://www.mcmaster.com/3881T101)**
    - [ ]  Document justification with respect to requirements (filter particulate size): [This](https://www.grainger.com/know-how/equipment-information/kh-what-is-merv-rating-air-filter-rating-chart) page says that a MERV rating of >13 is required to filter all pathogens
    - [ ]  Add to BoM
    - [ ]  Add to CAD
    - [ ]  Test filtration capabilities (?)
- [ ]  Design _Shutter Mechanism_
- [ ]  Design housing for fans, filters, shutters, and cartridge
- [ ]  Design oven-safe cartridge - Consider silica gel particle size (.5-1mm in diameter), we should consider a "mesh fabric bag" that sits within a harder shell cartridge
- [ ]  Fabricate and assemble subsystem
- [ ]  Test all features, document results
- [ ]  Write code to trigger operation on bang-bang *high humidity* status
